### ISSUE TITLE
The noses are not showing up ZACK....

### ISSUE THREAD

**Issue by Tayas23** [PfGirlsWhoCode/avatar-creator#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zachwhaley** [comment]
I spell my "Zach" actually 😁

**Comment by Tayas23** [comment]
NO ZACKKKKKKKKKKKKKKKKK IF YOU WERE HUMAN YOU WOULD KNOW HOW TO SPELL YOUR OWN NAME!
                                 -Natalia 💯

**Comment by alltheothers11** [comment]
i fixed it 💁‍♀️

**Comment by Tayas23** [comment]
OMG WOW MUFFIN!!!!

-Natalia 💯

**Comment by alltheothers11** [comment]
yea sometimes my brain cell decides to randomly work outta the blue
