### ISSUE TITLE
Hair can be added to the screen before an avatar body style and gender have been chosen.

### ISSUE THREAD

**Issue by jgatliff** [PfGirlsWhoCode/avatar-creator#30]
When I first enter the screen in Google Chrome and choose one of the hair lengths and colors, the hair appears even though there isn't an avatar body on the screen.

Expected behaviour is to check to make sure the avatar gender and body style have both been chosen before allowing hair to appear.

**Comment by AutumnK123533** [comment]
Me be working on it,,,,,,,, :3

**Comment by AutumnK123533** [comment]
I'm working on it.

**Comment by Kermit1208** [comment]
here's *tap tap* the mf *tap tap* tea! 💯 🍵 👌
