### ISSUE TITLE
Gibby! :)

### ISSUE THREAD

**Issue by Kermit1208** [PfGirlsWhoCode/avatar-creator#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kermit1208** [comment]
🍐

**Comment by Kermit1208** [comment]
You been hit by, you been hit by... Gibby! 😄

**Comment by zachwhaley** [comment]
![mj](https://user-images.githubusercontent.com/2996465/57859111-eec32e00-77b7-11e9-92ff-28bee847e635.gif)
